# Generated by Django 3.2.23 on 2024-01-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('PartnerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('IntegrationDetails', models.JSONField()),
                ('LastDataSentTimestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('EAN', models.CharField(max_length=13)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('ProductURL', models.URLField(max_length=1000)),
                ('LastScrapedTimestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('ScraperConfigID', models.AutoField(primary_key=True, serialize=False)),
                ('ConfigSettings', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=2)),
                ('LastUpdatedTimestamp', models.DateTimeField()),
                ('Version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('ProductSpecificationID', models.AutoField(primary_key=True, serialize=False)),
                ('SpecificationTimestamp', models.DateTimeField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrapper.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ScraperConfigID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrapper.scraperconfig'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('PriceID', models.AutoField(primary_key=True, serialize=False)),
                ('OriginalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SalePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ShippingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PriceTimestamp', models.DateTimeField()),
                ('PriceDate', models.DateField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrapper.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('FeedID', models.AutoField(primary_key=True, serialize=False)),
                ('FeedURL', models.CharField(max_length=255)),
                ('LastRetrievedTimestamp', models.DateTimeField()),
                ('FeedType', models.CharField(max_length=50)),
                ('LastStatus', models.CharField(max_length=50)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrapper.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntegrationDetails', models.JSONField()),
                ('LastDataSentTimestamp', models.DateTimeField()),
                ('PartnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrapper.partner')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scrapper.product')),
            ],
            options={
                'unique_together': {('ProductID', 'PartnerID')},
            },
        ),
    ]
