# Generated by Django 3.2.23 on 2024-01-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraperconfig',
            table='scraperconfig',
        ),
    ]
