# Generated by Django 4.2.7 on 2024-01-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ScraperConfigID',
        ),
        migrations.DeleteModel(
            name='ScraperConfig',
        ),
    ]
