# Generated by Django 4.2.7 on 2023-12-13 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lastscrapedtimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnerid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
