# Generated by Django 4.2.7 on 2024-01-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapper', '0002_remove_product_scraperconfigid_delete_scraperconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('ScraperConfigID', models.AutoField(primary_key=True, serialize=False)),
                ('ConfigSettings', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=2)),
                ('LastUpdatedTimestamp', models.DateTimeField()),
                ('Version', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ScraperConfigID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scrapper.scraperconfig'),
            preserve_default=False,
        ),
    ]
